/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Event = IDL.Record({
  'venue' : IDL.Text,
  'date' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
});
export const RegistrationFee = IDL.Record({
  'category' : IDL.Text,
  'amount' : IDL.Nat,
});
export const ScheduleItem = IDL.Record({
  'title' : IDL.Text,
  'time' : IDL.Text,
  'speaker' : IDL.Text,
  'location' : IDL.Text,
});
export const Speaker = IDL.Record({
  'topic' : IDL.Text,
  'name' : IDL.Text,
  'designation' : IDL.Text,
  'affiliation' : IDL.Text,
});

export const idlService = IDL.Service({
  'getAllEvents' : IDL.Func([], [IDL.Vec(Event)], ['query']),
  'getEvent' : IDL.Func([IDL.Text], [Event], ['query']),
  'getFees' : IDL.Func([], [IDL.Vec(RegistrationFee)], ['query']),
  'getSchedule' : IDL.Func([], [IDL.Vec(ScheduleItem)], ['query']),
  'getSpeakers' : IDL.Func([], [IDL.Vec(Speaker)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Event = IDL.Record({
    'venue' : IDL.Text,
    'date' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
  });
  const RegistrationFee = IDL.Record({
    'category' : IDL.Text,
    'amount' : IDL.Nat,
  });
  const ScheduleItem = IDL.Record({
    'title' : IDL.Text,
    'time' : IDL.Text,
    'speaker' : IDL.Text,
    'location' : IDL.Text,
  });
  const Speaker = IDL.Record({
    'topic' : IDL.Text,
    'name' : IDL.Text,
    'designation' : IDL.Text,
    'affiliation' : IDL.Text,
  });
  
  return IDL.Service({
    'getAllEvents' : IDL.Func([], [IDL.Vec(Event)], ['query']),
    'getEvent' : IDL.Func([IDL.Text], [Event], ['query']),
    'getFees' : IDL.Func([], [IDL.Vec(RegistrationFee)], ['query']),
    'getSchedule' : IDL.Func([], [IDL.Vec(ScheduleItem)], ['query']),
    'getSpeakers' : IDL.Func([], [IDL.Vec(Speaker)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };