/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Event {
  'venue' : string,
  'date' : string,
  'name' : string,
  'description' : string,
}
export interface RegistrationFee { 'category' : string, 'amount' : bigint }
export interface ScheduleItem {
  'title' : string,
  'time' : string,
  'speaker' : string,
  'location' : string,
}
export interface Speaker {
  'topic' : string,
  'name' : string,
  'designation' : string,
  'affiliation' : string,
}
export interface _SERVICE {
  'getAllEvents' : ActorMethod<[], Array<Event>>,
  'getEvent' : ActorMethod<[string], Event>,
  'getFees' : ActorMethod<[], Array<RegistrationFee>>,
  'getSchedule' : ActorMethod<[], Array<ScheduleItem>>,
  'getSpeakers' : ActorMethod<[], Array<Speaker>>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];